USE [GISData]
GO
/****** Object:  User [BUDGETBC\wsbhq401$]    Script Date: 2021-07-10 1:50:41 PM ******/
CREATE USER [BUDGETBC\wsbhq401$] FOR LOGIN [BUDGETBC\WSBHQ401$] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [BUDGETBC\wsbhq401$]
GO
