USE [GISData]
GO
/****** Object:  User [BUDGETBC\AIqbal]    Script Date: 2021-07-10 1:50:41 PM ******/
CREATE USER [BUDGETBC\AIqbal] FOR LOGIN [BUDGETBC\AIqbal] WITH DEFAULT_SCHEMA=[BUDGETBC\AIqbal]
GO
ALTER ROLE [ar_fee_processer] ADD MEMBER [BUDGETBC\AIqbal]
GO
