USE [GISData]
GO
/****** Object:  Table [dbo].[Rate_Shop_Batch]    Script Date: 2021-07-10 1:50:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rate_Shop_Batch](
	[Batch_ID] [int] IDENTITY(100000,1) NOT NULL,
	[Batch_Date] [datetime] NULL,
	[Batch_Description] [varchar](50) NULL,
 CONSTRAINT [PK_Rate_Shop_Batch] PRIMARY KEY CLUSTERED 
(
	[Batch_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
