USE [GISData]
GO
/****** Object:  Table [dbo].[Rate_Purpose]    Script Date: 2021-07-10 1:50:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rate_Purpose](
	[Rate_Purpose_ID] [smallint] IDENTITY(1,1) NOT NULL,
	[Rate_Purpose] [varchar](255) NOT NULL,
	[Maestro_Rate_Indicator] [char](1) NULL,
 CONSTRAINT [PK_Rate_Purpose] PRIMARY KEY CLUSTERED 
(
	[Rate_Purpose_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [UC_Rate_Purpose1] UNIQUE NONCLUSTERED 
(
	[Rate_Purpose] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
