USE [GISData]
GO
/****** Object:  Table [dbo].[FA_GL]    Script Date: 2021-07-10 1:50:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FA_GL](
	[FA_GL_ID] [int] IDENTITY(1,1) NOT NULL,
	[Accounting_Item] [varchar](75) NULL,
	[Vehicle_Type] [varchar](18) NULL,
	[GL_Number] [varchar](20) NULL,
	[Program] [bit] NULL,
 CONSTRAINT [PK_FA_GL] PRIMARY KEY CLUSTERED 
(
	[FA_GL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
