USE [GISData]
GO
/****** Object:  Table [dbo].[IB_AR_Detail]    Script Date: 2021-07-10 1:50:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IB_AR_Detail](
	[IB_AR_ID] [int] NOT NULL,
	[Revenue_Account] [char](45) NOT NULL,
	[Amount] [decimal](9, 2) NULL,
 CONSTRAINT [PK_IB_AR_Detail] PRIMARY KEY CLUSTERED 
(
	[IB_AR_ID] ASC,
	[Revenue_Account] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IB_AR_Detail]  WITH CHECK ADD  CONSTRAINT [FK_IB_AR_Detail_IB_AR_Header] FOREIGN KEY([IB_AR_ID])
REFERENCES [dbo].[IB_AR_Header] ([IB_AR_ID])
GO
ALTER TABLE [dbo].[IB_AR_Detail] CHECK CONSTRAINT [FK_IB_AR_Detail_IB_AR_Header]
GO
