USE [GISData]
GO
/****** Object:  Table [dbo].[OnlineMartOrder]    Script Date: 2021-07-10 1:50:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OnlineMartOrder](
	[Order_Number] [int] IDENTITY(1,1) NOT NULL,
	[Credit_Card_number] [varchar](20) NULL,
 CONSTRAINT [PK_OnlineMartOrder] PRIMARY KEY CLUSTERED 
(
	[Order_Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
