USE [GISData]
GO
/****** Object:  StoredProcedure [dbo].[stpr_get_company_list]    Script Date: 2021-07-10 1:50:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE  PROCEDURE [dbo].[stpr_get_company_list]
(
  @p_ORDER_BY AS VARCHAR(20),
  @p_DIRECTION AS VARCHAR(4)
)

AS
BEGIN
	SELECT COM.CONVERGE_COMPANY_ID AS CONVERGE_COMPANY_ID,
		COM.COMPANY_NAME AS COMPANY_NAME,
		COM.NAICS AS NAICS,
		(SELECT MAX(PHONE_CALLED_ON)
			FROM dbo.PHONE_LOG 
			WHERE COMPANY_ID = COM.CONVERGE_COMPANY_ID)  AS LASTCALLED,
		(SELECT MAX(CONVERT(SMALLINT, EXP_CALL_REQD))
			FROM dbo.PHONE_LOG
			WHERE COMPANY_ID = COM.CONVERGE_COMPANY_ID 
		) AS EXP_CALL_REQD,
		COM.CALL_BACK_FIRST AS CALL_BACK_FIRST,
		COM.CALL_BACK_LAST AS CALL_BACK_LAST,
		COM.CALL_BACK_PHONE AS CALL_BACK_PHONE,
		COM.CALL_DATE AS CALL_DATE,
		COM.PREFERED AS PREFERED,
		COM.NOTES AS NOTES
		
	FROM dbo.COMPANIES COM
	ORDER BY
		CASE WHEN @p_ORDER_BY = 'CompanyName' AND @p_DIRECTION = 'ASC' THEN COM.COMPANY_NAME END ASC,
		CASE WHEN @p_ORDER_BY = 'CompanyName' AND @p_DIRECTION = 'DESC' THEN COM.COMPANY_NAME END DESC,
		CASE WHEN @p_ORDER_BY = 'LastCalled' AND @p_DIRECTION = 'ASC' THEN 
			(SELECT MAX(PHONE_CALLED_ON)
			FROM dbo.PHONE_LOG 
			WHERE COMPANY_ID = COM.CONVERGE_COMPANY_ID) END ASC,
		CASE WHEN @p_ORDER_BY = 'LastCalled' AND @p_DIRECTION = 'DESC' THEN 
			(SELECT MAX(PHONE_CALLED_ON)
			FROM dbo.PHONE_LOG 
			WHERE COMPANY_ID = COM.CONVERGE_COMPANY_ID) END DESC,
		CASE WHEN @p_ORDER_BY = 'CallBack' AND @p_DIRECTION = 'ASC' THEN COM.CALL_DATE END ASC,
		CASE WHEN @p_ORDER_BY = 'CallBack' AND @p_DIRECTION = 'DESC' THEN COM.CALL_DATE END DESC
				


END




GO
