USE [GISData]
GO
/****** Object:  Table [dbo].[CSR_LogonTime]    Script Date: 2021-07-10 1:50:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CSR_LogonTime](
	[Location] [char](30) NOT NULL,
	[LogonTime] [int] NOT NULL,
 CONSTRAINT [PK_CSR_LogonTime] PRIMARY KEY CLUSTERED 
(
	[Location] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
