USE [GISData]
GO
/****** Object:  Table [dbo].[HubMaps]    Script Date: 2021-07-10 1:50:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HubMaps](
	[HubID] [smallint] NOT NULL,
	[MapImageName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_HubMaps] PRIMARY KEY CLUSTERED 
(
	[HubID] ASC,
	[MapImageName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
