USE [GISData]
GO
/****** Object:  Table [dbo].[WS_RA_Rec_Data]    Script Date: 2021-07-10 1:50:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WS_RA_Rec_Data](
	[Rec_ID] [int] IDENTITY(1,1) NOT NULL,
	[Rec_Data] [text] NULL,
 CONSTRAINT [PK_WS_RA_Rec_Data] PRIMARY KEY CLUSTERED 
(
	[Rec_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
