USE [GISData]
GO
/****** Object:  Table [dbo].[IB_AP_Detail]    Script Date: 2021-07-10 1:50:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IB_AP_Detail](
	[IB_AP_ID] [int] NOT NULL,
	[Expense_Account] [char](45) NOT NULL,
	[Amount] [decimal](9, 2) NULL,
 CONSTRAINT [PK_IB_AP_Detail] PRIMARY KEY CLUSTERED 
(
	[IB_AP_ID] ASC,
	[Expense_Account] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IB_AP_Detail]  WITH CHECK ADD  CONSTRAINT [FK_IB_AP_Detail_IB_AP_Header] FOREIGN KEY([IB_AP_ID])
REFERENCES [dbo].[IB_AP_Header] ([IB_AP_ID])
GO
ALTER TABLE [dbo].[IB_AP_Detail] CHECK CONSTRAINT [FK_IB_AP_Detail_IB_AP_Header]
GO
