USE [GISData]
GO
/****** Object:  User [GCUMMINGS]    Script Date: 2021-07-10 1:50:41 PM ******/
CREATE USER [GCUMMINGS] FOR LOGIN [BUDGETBC\GCUMMINGS] WITH DEFAULT_SCHEMA=[GCUMMINGS]
GO
ALTER ROLE [FleetAccounting] ADD MEMBER [GCUMMINGS]
GO
