USE [GISData]
GO
/****** Object:  Table [dbo].[FA_AP_Detail]    Script Date: 2021-07-10 1:50:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FA_AP_Detail](
	[AP_ID] [int] NOT NULL,
	[Expense_Account] [char](45) NOT NULL,
	[Amount] [decimal](9, 2) NULL,
 CONSTRAINT [PK_FA_AP_Detail] PRIMARY KEY CLUSTERED 
(
	[AP_ID] ASC,
	[Expense_Account] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
